### ISSUE TITLE
Missing subread read group in header

### ISSUE THREAD

**Issue by danielecook** [PacificBiosciences/align-clr-to-ccs#1]
https://github.com/PacificBiosciences/align-clr-to-ccs/blob/57b257111b6b793a986f616f1d681962133396c3/src/main.cpp#L308

I am sharding a subread bam using `zmwfilter`, then running `actc`.

`actc` finishes with `exit=0`, but running `pbindex` on the resulting file gives the following error:

```
>|> 20210908 17:35:57.500 -|- FATAL -|- Run -|- 0x7ff2bb5c0e80|| -|- pbindex ERROR: [pbbam] BAM header ERROR: read group ID not found: 301e4efa
```

That ID comes from the subread header. The actual header contains the read ID from the CCS bam.

However, if I run the following, `pbindex` succeeds:

```bash
actc -j ${task.cpus} ${subreads_bam} ${ccs_bam} out.bam

# The block below will add the subread read group to the header.
{
  samtools view -H out.bam;
  samtools view -H ${subreads_bam} | egrep '@RG';
} > new_header.txt
samtools reheader new_header.txt out.bam > ${subreads_to_ccs_bam}

pbindex ${subreads_to_ccs_bam} # exit=0
```

Can you please double check that the correct read groups are added to the sam header? I see the CCS read group but I think it should be the subread read group.

**Comment by armintoepfer** [comment]
I'll have a look

**Comment by armintoepfer** [comment]
Fixed it in https://github.com/PacificBiosciences/align-clr-to-ccs/commit/e5779b786414cfe48a7e2bdefd522d5aac9ed003
Also uploaded a new binary with all optimizations.

**Comment by hhl1999** [comment]
@armintoepfer 

I'm sorry, I didn't understand you. Where should I copy your program?

**Comment by armintoepfer** [comment]
https://github.com/PacificBiosciences/actc/releases/tag/0.2.0

**Comment by hhl1999** [comment]
I'm very sorry, I didn't make it clear just now

I have also encountered this problem, but it is the problem of using pbsv

`>|> 20220624 06:30:06.255 -|- FATAL -|- Run -|- 0x7fc84c072b80|| -|- pbsv discover ERROR: [pbbam] BAM header ERROR: read group ID not found: `

CCS BAM input:
`pbmm2 align ref.fa movie1.ccs.bam ref.movie1.bam --sort --preset CCS --sample sample1`

But my bam file contains read group id, so do you know what's the error mean?
