### ISSUE TITLE
Run-time dependency Boost found: NO (tried system)

### ISSUE THREAD

**Issue by AhmedArslan** [PacificBiosciences/align-clr-to-ccs#3]
Now able to install properly, any tips would be helpful?

meson --prefix ~/tools/align-clr-to-ccs-0.1.0
The Meson build system
Version: 0.61.1
Source dir: /tools/align-clr-to-ccs-0.1.0
Build dir: /tools/align-clr-to-ccs-0.1.0/build
Build type: native build
Project name: actc
Project version: 0.1.0
C++ compiler for the host machine: c++ (gcc 7.5.0 "c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
C++ linker for the host machine: c++ ld.bfd 2.30
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C++ supports arguments -Werror=strict-aliasing: YES 
Compiler for C++ supports arguments -Wno-unused-parameter: YES 
Compiler for C++ supports arguments -Wno-unused-local-typedef: NO 
Run-time dependency threads found: YES
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency Boost found: NO (tried system)

../meson.build:29:0: ERROR: Dependency "boost" not found, tried system

A full log can be found at /tools/align-clr-to-ccs-0.1.0/build/meson-logs/meson-log.txt

Although boost is installed, already :
b2 -h
Invalid option: -h

usage: b2 [ options ] targets...

-a      Build all targets, even if they are current.
-dx     Set the debug level to x (0-13,console,mi).
-fx     Read x instead of bootstrap.
-jx     Run up to x shell commands concurrently.
-lx     Limit actions to x number of seconds after which they are stopped.
-mx     Maximum target output saved (kb), default is to save all output.
-n      Don't actually execute the updating actions.
-ox     Mirror all output to file x.
-px     x=0, pipes action stdout and stderr merged into action output.
-q      Quit quickly as soon as a target fails.
-sx=y   Set variable x=y, overriding environment.
-tx     Rebuild x, even if it is up-to-date.
-v      Print the version of jam and exit.
--x     Option is ignored.

**Comment by armintoepfer** [comment]
Hi. I'm not supporting build problems. You can find a fully static binary under releases for those who can't build it themselves.
