### ISSUE TITLE
actc hangs

### ISSUE THREAD

**Issue by peterdfields** [PacificBiosciences/align-clr-to-ccs#4]
Hi,

I initially tried actc without the chunking option but found the machine I was using was running into memory limitations. When I try using sequential chunking using:

```
END=1000
for i in $(seq 1 $END); do ~/bioinformatics/align-clr-to-ccs/build/src/actc m64041_211102_060946.subreads.bam m64041_211102_060946.hifi_reads.bam aligned.bam -j 0 --chunk $i/1000; done
```

things seem to be running fine but then the program hangs without producing any sort of error message. I ran the software with DEBUG log option on and I see the following:

```
| 20220125 17:37:32.303 | DEBUG | SEEKING
| 20220125 17:37:32.324 | DEBUG | CLR : m64041_211102_060946/65079336/0_1520
| 20220125 17:37:32.324 | DEBUG | CLR : m64041_211102_060946/65079336/1561_18436
| 20220125 17:37:32.325 | DEBUG | CLR : m64041_211102_060946/65079336/18479_35605
| 20220125 17:37:32.325 | DEBUG | CLR : m64041_211102_060946/65079336/35650_52512
| 20220125 17:37:32.325 | DEBUG | CLR : m64041_211102_060946/65079336/52556_69705
| 20220125 17:37:32.325 | DEBUG | CLR : m64041_211102_060946/65079336/69750_86540
| 20220125 17:37:32.325 | DEBUG | CLR : m64041_211102_060946/65079336/86584_103555
| 20220125 17:37:32.325 | DEBUG | CLR : m64041_211102_060946/65079336/103602_120450
| 20220125 17:37:32.325 | DEBUG | CLR : m64041_211102_060946/65079336/120494_137568
| 20220125 17:37:32.325 | DEBUG | CLR : m64041_211102_060946/65079336/137615_143265
| 20220125 17:37:32.325 | DEBUG | CCS : m64041_211102_060946/65079341/ccs
| 20220125 17:37:32.325 | DEBUG | CLR : m64041_211102_060946/65079341/0_24825
| 20220125 17:37:34.073 | INFO | Progress 10%
```
Please let me know if any additional information would be helpful for diagnosing this issue.

**Comment by armintoepfer** [comment]
Memory scales with number of threads not chunk size.

I haven't encountered any hangs so far. Maybe try to generate a fresh `subreads.bam.pbi`. Have you tried the official binary and not your own?

**Comment by peterdfields** [comment]
Hi @armintoepfer 

It appears the issue was a truncated bam (determined when I tried to reindex the file upon your suggestion), so something must have gone wrong on the download. I re-downloaded the subreads.bam file and indexing completed successfully. So far actc is moving through the chunks where hangs occurred before. Thank you again for your assistance.
